### PR TITLE
Update Styles

### PR DESCRIPTION
**Pull request by mbthiery**
- Fix nav overlap with hotspots on desktop #21 
- Inverted the nav on mobile #20
- Dealt with existing + new z-index issues
- Tighten up hotspot list styling

Screenshot 2023-04-17 at 3 54 43 PM
Screenshot 2023-04-17 at 3 54 39 PM
Screenshot 2023-04-17 at 3 54 31 PM
Screenshot 2023-04-17 at 3 54 21 PM

### CODE REVIEW

**Review by jthiller — APPROVED** [review]

**Comment by dansku** [comment]
looking great guys!

**Comment by dansku** [comment]
i think this was unnoticed 

image

**Comment by jthiller** [comment]
aye matthew grabbing that now

-Joey Hiller

**Comment by mbthiery** [comment]
https://github.com/helium/network-explorer/pull/24

**Pull request merged**
